name: GDHI-Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build GDHI-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3
      - name: Install curl
        run: sudo apt install curl
      - name: Install nvm
        run: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh
      - run: export NVM_DIR="$HOME/.nvm"
      - run: source $NVM_DIR/nvm.sh
      - run: source ~/.bashrc
      - name: Install dependencies of GDHI-app
        shell: bash -l {0}
        run: nvm install 16.19.0
      - run: nvm use
      - run: yarn install
      - run: yarn test
      - run: yarn build
