name: GDHI-Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build GDHI-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3

      - name: Install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies of GDHI-app
        run: yarn install

      - name: Run test cases for the GDHI-app
        run: yarn test
        continue-on-error: true

      - name: Build GDHI-app
        run: yarn build
