name: GDHI-Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  node_version: 16.19.0
jobs:
  build:
    name: Build GDHI-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3

      - name: Use Node.js $node_version
        uses: actions/setup-node@v3
        with:
          node-version: $node_version

      - name: Install dependencies of GDHI-app
        run: npm install

      - name: Run test cases for the GDHI-app
        run: npm test

      - name: Build GDHI-app
        run: npm run build --if-present
