name: GDHI-Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build GDHI-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt install curl

      - name: Install nvm
        run: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh

      - run: export NVM_DIR="$HOME/.nvm"
      - run: source $NVM_DIR/nvm.sh
      - run: source ~/.bashrc

      - name: Install Node v16
        shell: bash -l {0}
        run: nvm install 16.19.0

      - name: Use the node installed
        shell: bash -l {0}
        run: nvm use

      - name: Install dependencies of GDHI-app
        run: yarn install

      - name: Run test cases for the GDHI-app
        run: yarn test
        continue-on-error: true

      - name: Build GDHI-app
        run: yarn build
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
