name: CI-CD Pipeline 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Github
        uses: actions/checkout@v3

      - name: Install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies of GDHI-app
        run: yarn install

      - name: Run test cases for the GDHI-app
        run: yarn test:coverage
        continue-on-error: true

      - name: Build GDHI-app
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Artifact to s3
        run: aws s3 cp dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/${{ secrets.AWS_S3_FOLDER }}/ --recursive

  deploy-to-qa:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CodeDeploy Deployment for QA
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.AWS_QA_DEPLOYMENT_GROUP }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --ignore-application-stop-failures

  deploy-to-showcase:
    runs-on: ubuntu-latest
    environment: SHOWCASE
    needs: [deploy-to-qa]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CodeDeploy Deployment for Showcase
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.AWS_SHOWCASE_DEPLOYMENT_GROUP }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --ignore-application-stop-failures

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: [deploy-to-showcase]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create CodeDeploy Deployment for Prod
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.AWS_PROD_DEPLOYMENT_GROUP }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --ignore-application-stop-failures
